CREATE DATABASE IF NOT EXISTS novatech_store CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE novatech_store;

CREATE TABLE IF NOT EXISTS app_state (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  products_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO app_state (id, products_json)
VALUES (1, '[]')
ON DUPLICATE KEY UPDATE products_json = products_json;

CREATE TABLE IF NOT EXISTS leads (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  last_name VARCHAR(120) NULL,
  company VARCHAR(180) NULL,
  phone VARCHAR(60) NOT NULL,
  email VARCHAR(190) NOT NULL,
  message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);